image:
  repository: smoothoperator228
  name: userservice
  tag: latest

migrations:
  image:
    repository: smoothoperator228
    name: migrations
    tag: latest
  config:
    POSTGRESQL_URL: "postgres://admin:admin@postgres:5432/db?sslmode=disable"
    VERSION: "000001"

configs:
  POSTGRES_DB: db
  POSTGRES_HOST: postgres:5432

secrets:
  POSTGRES_USER: "YWRtaW4=" # admin
  POSTGRES_PASSWORD: "YWRtaW4=" # admin

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/product
  port: http
