apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-messaging-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: product-service-messaging               # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
      labels:
        app: product-service-messaging               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      initContainers:
        - name: run-migrations-product
          image: smoothoperator228/migrations-messaging:latest
          command: ["migrate", "-path", "/migrations", "-database", "$(POSTGRESQL_URL)", "goto", "$(VERSION)"]
          env:
            - name: POSTGRESQL_URL
              value: "postgres://admin:admin@postgres:5432/db?sslmode=disable"
            - name: VERSION
              value: "000001"
      containers:
        - image: smoothoperator228/productservice-messaging:latest       # образ Docker
          imagePullPolicy: IfNotPresent
          name: product-service-messaging          # ім'я контейнеру
          ports:
            - containerPort: 8080  # порт по якому можна звертатись до поди
          envFrom:
            - configMapRef:
                name: product-service-messaging-config
            - secretRef:
                name: product-service-messaging-secret