apiVersion: v1
kind: Service
metadata:
  name: product-service-messaging-service
spec:
  type: ClusterIP
  ports:
    - port: 80         # порт по якому можна звератись до сервісу
      targetPort: 8080 # порт контейнера
    # nodePort: 32001 # порт на якому буде доступний сервіс ззовні
  selector:
    app: product-service-messaging