apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - image: smoothoperator228/clientservice:latest
          imagePullPolicy: IfNotPresent
          name: client-service
          ports:
            - containerPort: 80